# Generated by Django 2.2.6 on 2020-10-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_auto_20201013_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='biz_id',
            field=models.CharField(default=2, max_length=50, verbose_name='业务id'),
        ),
    ]
