# Generated by Django 2.2.6 on 2020-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_hosts_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='script_type',
            field=models.IntegerField(choices=[(1, 'shell脚本'), (2, 'bat脚本'), (3, 'perl脚本'), (4, 'python脚本'), (5, 'Powershell脚本')], default=1, verbose_name='脚本类型'),
        ),
    ]
