# Generated by Django 2.2.6 on 2020-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_scripts_script_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_app_code', models.CharField(max_length=50, verbose_name='app_code')),
                ('bk_app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('introduction', models.CharField(max_length=50, verbose_name='应用介绍')),
                ('creator', models.CharField(max_length=50, verbose_name='创建者')),
                ('developer', models.CharField(max_length=50, verbose_name='开发人员')),
                ('server', models.CharField(max_length=50, verbose_name='隶属服务器')),
            ],
            options={
                'verbose_name': '应用表',
                'verbose_name_plural': '应用表',
                'db_table': 'Apps',
            },
        ),
    ]
