# Generated by Django 2.2.6 on 2020-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_auto_20201019_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='bk_app_code',
            field=models.CharField(max_length=200, verbose_name='app_code'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='bk_app_name',
            field=models.CharField(max_length=200, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='creator',
            field=models.CharField(max_length=200, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='developer',
            field=models.CharField(max_length=200, verbose_name='开发人员'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='introduction',
            field=models.CharField(max_length=200, verbose_name='应用介绍'),
        ),
    ]
